import requests

# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r".\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


CONVERSIONS = ""
CURRENCY_ENTRY = ""
window = Tk()
window.title("Currency Converter")

window.geometry("636x383")
window.configure(bg = "#C9BABA")

def get_entry():
    global CONVERSIONS, CURRENCY_ENTRY
    
    CONVERSIONS = ""
    CURRENCY_ENTRY = entry_1.get().upper()
    base = CURRENCY_ENTRY
    if base == "Q":
        window.destroy()

    data = convert_currency(base)

    print(data)
    del data[base]
    print("conversions", CONVERSIONS)

    for ticker, value in data.items():
        CONVERSIONS += f"{ticker}: {value:.3f}\n"
        print(f"{ticker}: {value}")
    canvas.itemconfig(tagOrId=conversions_title_text,
                          text=f"Conversion From\n{base} To")
    canvas.itemconfig(tagOrId=text_shown, text=f"\n{CONVERSIONS}")
    


canvas = Canvas(
    window,
    bg = "#C9BABA",
    height = 383,
    width = 636,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    636.0,
    80.0,
    fill="#3B5BCD",
    outline="")

canvas.create_text(
    39.0,
    20.0,
    anchor="nw",
    text="CURRENCY CONVERTER",
    fill="#FFFFFF",
    font=("KdamThmor", 28 * -1)
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    569.0,
    40.0,
    image=image_image_1
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    173.0,
    160.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=71.0,
    y=136.0,
    width=204.0,
    height=47.0
)

canvas.create_text(
    54.0,
    105.0,
    anchor="nw",
    text="Enter currency code:",
    fill="#000000",
    font=("MontserratRoman Regular", 16 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: get_entry(),
    relief="flat"
)

button_1.place(
    x=75.0,
    y=215.0,
    width=197.0,
    height=58.0
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    491.0,
    220.0,
    image=image_image_2
)

conversions_title_text = canvas.create_text(
    391.0,
    117.0,
    anchor="nw",
    text="Conversions:",
    fill="#000000",
    font=("MontserratRoman Regular", 20 * -1)
)

text_shown = canvas.create_text(
    397.0,
    160.0,
    anchor="nw",
    text="Data Here!!",
    fill="#000000",
    font=("MontserratRoman Regular", 20 * -1)
)
window.resizable(False, False)

#ACTUAL CODE:--------------------------------------------------------------------------------------------------

API_KEY = 'YOUR OWN API KEY'
BASE_URL = f"https://api.freecurrencyapi.com/v1/latest?apikey={API_KEY}"


#change the currencies here for what you want
CURRENCIES = ["INR", "CAD", "EUR", "AUD", "USD"]


def convert_currency(base):
    currencies = ",".join(CURRENCIES)
    url = f"{BASE_URL}&base_currency={base}&currencies={currencies}"
    try:
        response = requests.get(url)
        data = response.json()
        return data["data"]
    except:
        print("Invalid currency.")
        return None


window.mainloop()
